version: '3.8'

services:

  ft_pong:
    container_name: ft_pong
    image: ft_pong
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - ft-ping
    restart: on-failure
    env_file:
      - .env

networks:
  ft-ping: {}
