version: '3.8'

services:

  ft_pong:
    container_name: ft_pong
    image: ft_pong
    build:  
      context: .
      dockerfile: Dockerfile
    environment:
      - $PASSWORD=${PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - ft-ping
    restart: on-failure

networks:
  ft-ping: {}
